### ISSUE TITLE
get/set all values referred by an optic

### ISSUE THREAD

**Issue by aplavin** [JuliaObjects/Accessors.jl#63]
Some existing optics, such as `Elements()`, `If()` and `Recursive()`, can only be `modify`ed - one cannot retrieve the values specified by them. I understand that it's not obvious how to implement `optic(obj)` for them and even what type it should return. However, from time to time I try to reach for this functionality: either to specifically extract the corresponding values, or just to see what values `modify` would be called with.

Do you think it's possible to design value extraction for those optics in a consistent manner?

**Comment by jw3126** [comment]
A quick and dirty way to do this is:
```julia
out = Any[]
modify(obj, optic) do val
    push!(out, val)
    f(val)
end
```
@rafaqz has done a lot of work in this direction, see https://github.com/JuliaObjects/Accessors.jl/pull/23
Ultimately we could not find a performant way to implement this, that's why the PR is not merged.

**Comment by jw3126** [comment]
Okay, so is your question whether one can implement `optic(obj)` for these such that the lens laws are satisfied?

I think that is not really possible. For instance:
```julia
julia> using Accessors

julia> obj = [1,2,3]
3-element Vector{Int64}:
 1
 2
 3

julia> optic = Elements()
Elements()

julia> modify(identity, obj, optic)
3-element Vector{Int64}:
 1
 2
 3

julia> set(obj, optic, 1)
3-element Vector{Int64}:
 1
 1
 1
```
That means you can only ever construct constant vectors using `set`, `Elements()`, but you can produce arbitrary vectors using `modify`, `Elements()`. So there is no hope to decompose `modify` into `set` and "get".

Mathematically there are many flavors of optics and these can have different APIs and laws. Lens is one with lots of structure and laws. `Elements()` only satisfies the functor laws and does not have a "get" operation:
* `@assert modify(identity, optic, obj) == obj`
* `@assert modify(f ∘g, optic, obj) == modify(f, optic, modify(g, optic, obj))`

**Comment by rafaqz** [comment]
> #23 looks a bit over my head - not even talking about implementation, I don't fully understand the interface and usecases.
> Extracting values with `Elements` and `If` is probably much easier to implement performantly than very general #23 queries. A major issue is the interface: it should be consistent with
> https://github.com/JuliaObjects/Accessors.jl/blob/fa0a446dab58fc6bcfc5e97413c441da04ec3e02/src/testing.jl#L18-L24

The use case is reconstructing arbitrary immutable objects with new/modified field values.

https://github.com/rafaqz/ModelParameters.jl is the best example of how powerful this can be.

You can also use it to e.g. replace `Array`s deeply nested in wrapper types with `GPUArray`s. You dont need to know or specify the fields, just the types to replace.

You can replace values using this method, by passing in a tuple. But the order of the matched field types in the object tree determines the order objects are replaced in.

**Comment by jw3126** [comment]
If you manage to implement a fast `get_all` that would be super awesome. In #23 we were not able to implement a `get_all` that type inference liked.

**Comment by rafaqz** [comment]
> That describes the whole Accessors.jl :)

Maybe you miss the paet about _arbitrary_ objects. Most of Accessors works on objects where you know a field name or some other detail. But sometimes we don't know anythong about the structure of the objects or the names of any of fields, and want to make generic changes to it.

Maybe its already possible with accessors? But Im not sure how. 

If you can define a function that takes the Float64 from any bits type object of any nesting depth and makes them all Float32 - and any other similar transformation - calculated at compile time. That would remove the need for that PR.

How youre describing `get_all` and `set_all` is essentially what my PR does, and it composes with other optics.

**Comment by rafaqz** [comment]
I dont realy get what is different with your proposal to that PR or what you dont understand at this point 😆

It has to be able to replace Flatten.jl and power ModelParameters.jl, as I linked earlier. That was my main goal, with some nice `@setall` syntax on top. 

By composes I mean you could do something like  `@setall` of the `val` fields of every `United.Quanty` in an object, using an optic. I cant remember the syntax to do that.

Maybe you should try it out rather than reinvent that wheel, if you will likely have the same type stability issue.

**Comment by rafaqz** [comment]
I don't know how `Elements` works really, but you can do things like this with arbitrary optics where `_[2].g` is:

```julia
@getall (x[2].g for x in missings_obj if x isa NamedTuple))
@setall (x[2].g for x in missings_obj if x isa NamedTuple) = 5
```

This example gets all the`g` properties of the second value in every `NamedTuple` in any object , or sets them all to equal 5.

See:
https://github.com/rafaqz/Accessors.jl/blob/queries/test/test_queries.jl

**Comment by rafaqz** [comment]
"Get me every `Float64` in this thing" seems like incredibly generic functionality to me ;)

**Comment by rafaqz** [comment]
I mean its not really worth arguing over which appoach is more general or "arguably more specialised", Im not sure why that's relevent.

**Comment by rafaqz** [comment]
Ok hah. Maybe we are talking past each other?

Sure, your proposal is generic in relation to other optics. But not in terms of the interaction with other packages, e.g. like Optim.jl.

Getting and setting everything as a flat tuple is a nice generic interface for the rest of the ecosystem. It removes all structure and complexity of objects.

Thats the reason Query is written like it is rather than using `Recursive`. Its the reason Flatten.jl exists: to create a simple interface between complex objects and all the use cases for flat vector/tuple inputs are required by many packages.

**Comment by rafaqz** [comment]
Getting can be inferrable and is in Flatten.jl, and get/set used to compile away in Flatten.jl before compiler changes killed that.

Its still some nanoseconds in the query PR here and can compile away when you use Revise.jl (a compiler bug). But not without it, and some use cases have a hard requirement that it compiles away.

Setting is harder in terms of implementation because you need to pass the state of your iterator around as you walk the tree. The leaves need to know about their position in the tree somehow. Getting doesnt need that, the order is implicit.

**Comment by jw3126** [comment]
> Setting is the hard part, getting is clearly trivial.

Mhh I think getting is already non trivial IIRC in #23 getall was not inferrable either.

**Comment by rafaqz** [comment]
But the code is much simpler. Its only a few lines in Flatten.jl and it it compiles away.

**Comment by rafaqz** [comment]
I dont think that its actually the same as `setall` on `Recursive`? `Recursive` returns nested tuples, not flat tuples.

Doesn't that mean it would set from nested tuples too? How is it a superset of `Query`? 

To use flat tuple inputs we will still need some `Query`-like function to build the nested tuples to pass to `Recursive`.

A more minor difference is `Recursive` only has a descent condition. `Query` also has a select condition - objects you take without descending into them, so the descend condition lets you ignore some objects completely.


`Recursive` should totally do what you want, but I cant see how it replaces `Query`.


By trivial I mean in the development of Flatten.jl the getall analog was a very small fraction of dev time, and it compiles away. setall was the majority of it and it still doesnt.

**Comment by rafaqz** [comment]
I dont think that its actually the same as `setall` on `Recursive`? `Recursive` returns nested tuples, not flat tuples.

Doesn't that mean it would set from nested tuples too? Then how is it a superset of `Query`? 

To use flat tuple inputs we will still need some `Query`-like function to build the nested tuples to pass to `Recursive`.

A more minor difference is `Recursive` only has a descent condition. `Query` also has a select condition - objects you take without descending into them, so the descend condition lets you ignore some objects completely.


`Recursive` should totally do what you want, but I cant see how it replaces `Query`.


By trivial I mean in the development of Flatten.jl the getall analog was a very small fraction of dev time, and it compiles away. setall was the majority of it and it still doesnt. getall on `Query` is not much more than splatted getall on `Recursive`. But setall in Query needs to get structural information from the object to know how to iterate the input. `Recusive` won't need that because the input is structured as nested tuples already.

**Comment by rafaqz** [comment]
Ok right of course it doesnt. I dont actually use Recursive. But as far as I know there's nowhere in Accessors.jl that flattens anything now.

But if you can handle distributing a flat tuple through all comppsed optics and setting the right part of the object with the right values of the tuple that will be great. 

It might be easiest to not pass around the iterator as in Query and instead just to call getall at every iteration, see how long the tuple it returns is, and pass a tuple that long with setall.

One last problem I haven't mentioned is that Query also only reconstructs objects when there were changes to their contents, to avoid trying to construct objects that dont implement `constructorof`. It's important for setall to not be overly fragile in the real world julia ecosystem, its the main downfall of Flatten.jl.

**Comment by rafaqz** [comment]
The inference problem is specifically with recursion, so you should be fine.

**Comment by rafaqz** [comment]
Possible using the new 1.8 `@assume_effects` macro will solve all of these problems. The problem will be splitting the compile time and runtime problems - `x isa Int` is very different condition to `x == 5` for the compiler, but we are treating them as the same. We can force the first to compile away with `@assume_effects`, but not the second.

**Comment by rafaqz** [comment]
It won't because th value in the struct is still determined at runtime.

I think we need the opposit - a separate path for descend to just check types match rather than calling a function that returns a Bool. Then we can use `@assume_effects` on that path.

**Comment by jw3126** [comment]
One issue that I am not sure is addressed by this PR would be
https://github.com/JuliaLang/julia/issues/43296#issuecomment-989868445
